version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - library_network
      
  react:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - library_network

networks:
  library_network:
    external: false


volumes:
  pgdata:

networks:
  library_network:
